# Generated by Django 2.1.1 on 2020-04-16 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('adminid', models.IntegerField(db_column='adminID', primary_key=True, serialize=False)),
                ('adminemail', models.CharField(db_column='adminEmail', max_length=100)),
                ('adminpassword', models.CharField(db_column='adminPassword', max_length=50)),
            ],
            options={
                'db_table': 'administrators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contractorapplications',
            fields=[
                ('contractorid', models.IntegerField(db_column='contractorID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ssn', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=150)),
                ('aptnum', models.CharField(db_column='aptNum', max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('willingtravel', models.IntegerField(db_column='willingTravel')),
                ('phone', models.IntegerField()),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('dateapp', models.DateField(db_column='dateApp')),
                ('dateapproved', models.DateField(db_column='dateApproved')),
            ],
            options={
                'db_table': 'contractorApplications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('contractid', models.IntegerField(db_column='contractID', primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('dateservice', models.DateField(db_column='dateService')),
                ('starttime', models.TimeField(db_column='startTime')),
                ('servicezipcode', models.IntegerField(db_column='serviceZipCode')),
                ('serviceaddress', models.CharField(db_column='serviceAddress', max_length=150)),
                ('serviceaptnum', models.CharField(db_column='serviceAptNum', max_length=10)),
                ('datecontract', models.DateTimeField(db_column='dateContract')),
                ('cancelcontract', models.IntegerField(db_column='cancelContract')),
            ],
            options={
                'db_table': 'contracts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paymentinfo',
            fields=[
                ('paymentid', models.IntegerField(db_column='paymentID', primary_key=True, serialize=False)),
                ('cardtype', models.CharField(db_column='cardType', max_length=20)),
                ('cardname', models.CharField(db_column='cardName', max_length=150)),
                ('cardnumber', models.IntegerField(db_column='cardNumber')),
                ('cvv', models.IntegerField()),
                ('billingaddress', models.CharField(db_column='billingAddress', max_length=150)),
                ('expdate', models.DateField(db_column='expDate')),
            ],
            options={
                'db_table': 'paymentInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serviceapplications',
            fields=[
                ('serviceappid', models.IntegerField(db_column='serviceAppID', primary_key=True, serialize=False)),
                ('dateapp', models.DateField(db_column='dateApp')),
                ('dateapproved', models.DateField(db_column='dateApproved')),
            ],
            options={
                'db_table': 'serviceApplications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicecategories',
            fields=[
                ('categoryserviceid', models.IntegerField(db_column='categoryServiceID', primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'serviceCategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('serviceid', models.IntegerField(db_column='serviceID', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('time_slot_id', models.IntegerField(db_column='time_slot_ID', primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('starttime', models.TimeField(db_column='startTime')),
                ('endtime', models.TimeField(db_column='endTime')),
            ],
            options={
                'db_table': 'time_slots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.IntegerField(db_column='userID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=20)),
                ('lastname', models.CharField(db_column='lastName', max_length=20)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('aptnum', models.CharField(db_column='aptNum', max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField(db_column='zipCode')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contractors',
            fields=[
                ('contractorid', models.ForeignKey(db_column='contractorID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hns.Contractorapplications')),
                ('name', models.CharField(max_length=100)),
                ('ssn', models.IntegerField(unique=True)),
                ('scheduleid', models.IntegerField(db_column='scheduleID', unique=True)),
                ('address', models.CharField(max_length=150)),
                ('aptnum', models.CharField(db_column='aptNum', max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField(db_column='zipCode')),
                ('willingtravel', models.IntegerField(db_column='willingTravel')),
                ('phone', models.IntegerField()),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'contractors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contractpayment',
            fields=[
                ('contractid', models.ForeignKey(db_column='contractID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hns.Contracts')),
                ('time', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved', models.IntegerField()),
                ('refund', models.IntegerField()),
            ],
            options={
                'db_table': 'contractPayment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractorsBackground',
            fields=[
                ('contractorid', models.ForeignKey(db_column='contractorID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hns.Contractors')),
                ('approved', models.IntegerField()),
            ],
            options={
                'db_table': 'contractors_background',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contractorsservicerecords',
            fields=[
                ('contractorid', models.ForeignKey(db_column='contractorID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hns.Contractors')),
                ('chargeservice', models.DecimalField(db_column='chargeService', decimal_places=2, max_digits=10)),
                ('yearsexperience', models.IntegerField(db_column='yearsExperience')),
            ],
            options={
                'db_table': 'contractorsServiceRecords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('contractorid', models.ForeignKey(db_column='contractorID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hns.Contractors')),
                ('number_rating', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('scheduleid', models.ForeignKey(db_column='scheduleID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hns.Contractors')),
                ('busy_available', models.IntegerField(db_column='busy/available')),
            ],
            options={
                'db_table': 'schedules',
                'managed': False,
            },
        ),
    ]
