# Generated by Django 2.1.1 on 2020-04-20 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
