# Generated by Django 2.1.1 on 2020-04-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hns', '0002_auto_20200420_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractorapplications',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='contractors',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='contracts',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='paymentinfo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='serviceapplications',
            options={'managed': True},
        ),
    ]
