# Generated by Django 3.0.5 on 2020-04-24 21:09

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('hns', '0003_auto_20200424_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorapplications',
            name='ssn',
            field=localflavor.us.models.USSocialSecurityNumberField(max_length=11, unique=True),
        ),
    ]
