# Generated by Django 3.0.5 on 2020-04-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hns', '0005_auto_20200424_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorapplications',
            name='ssn',
            field=models.IntegerField(unique=True),
        ),
    ]
