# Generated by Django 3.0.5 on 2020-04-25 20:49

from django.db import migrations
import hns.models


class Migration(migrations.Migration):

    dependencies = [
        ('hns', '0008_auto_20200425_2045'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', hns.models.MyUsersManager()),
            ],
        ),
    ]
