# Generated by Django 3.0.5 on 2020-04-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hns', '0010_users_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
    ]
