# Generated by Django 3.0.5 on 2020-04-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hns', '0011_auto_20200425_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractors',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
