# Generated by Django 3.0.5 on 2020-04-28 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hns', '0013_auto_20200426_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='contracts',
            name='userid',
            field=models.ForeignKey(db_column='userID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hns.Users'),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='userid',
            field=models.ForeignKey(db_column='userID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hns.Users'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='userid',
            field=models.ForeignKey(db_column='userID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hns.Users'),
        ),
    ]
