# Generated by Django 3.0.5 on 2020-04-28 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hns', '0014_auto_20200428_0146'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_login',
        ),
    ]
