# Generated by Django 3.0.5 on 2020-04-28 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hns', '0013_auto_20200426_0412'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
