# Generated by Django 3.0.5 on 2020-05-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hns', '0015_auto_20200428_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorapplications',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
