# Generated by Django 3.0.5 on 2020-05-02 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hns', '0017_auto_20200502_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceapplications',
            name='chargeservice',
            field=models.DecimalField(db_column='chargeService', decimal_places=2, default=7.25, max_digits=10),
        ),
        migrations.AddField(
            model_name='serviceapplications',
            name='yearsexperience',
            field=models.IntegerField(db_column='yearsExperience', default=0),
        ),
    ]
