# Generated by Django 3.0.5 on 2020-05-03 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hns', '0019_auto_20200502_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_login',
        ),
        migrations.AddField(
            model_name='contractorapplications',
            name='adminid',
            field=models.ForeignKey(db_column='adminID', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='hns.Administrators'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='contractorid',
            field=models.ForeignKey(db_column='contractorID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hns.Contractors'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='paymentid',
            field=models.ForeignKey(db_column='paymentID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hns.Paymentinfo'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='serviceid',
            field=models.ForeignKey(db_column='serviceID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hns.Services'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='userid',
            field=models.ForeignKey(db_column='userID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hns.Users'),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='userid',
            field=models.ForeignKey(db_column='userID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hns.Users'),
        ),
        migrations.AddField(
            model_name='rating',
            name='userid',
            field=models.ForeignKey(db_column='userID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hns.Users'),
        ),
        migrations.AddField(
            model_name='serviceapplications',
            name='adminid',
            field=models.ForeignKey(db_column='adminID', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='hns.Administrators'),
        ),
        migrations.AddField(
            model_name='serviceapplications',
            name='contractorid',
            field=models.ForeignKey(db_column='contractorID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hns.Contractors'),
        ),
        migrations.AddField(
            model_name='serviceapplications',
            name='serviceid',
            field=models.ForeignKey(db_column='serviceID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hns.Services'),
        ),
        migrations.AlterField(
            model_name='contractors',
            name='contractorid',
            field=models.ForeignKey(db_column='contractorID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hns.Contractorapplications'),
        ),
        migrations.AlterField(
            model_name='contractors',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='contractorid',
            field=models.ForeignKey(db_column='contractorID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hns.Contractors'),
        ),
        migrations.AlterField(
            model_name='serviceapplications',
            name='dateapproved',
            field=models.DateField(db_column='dateApproved', default=None),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('contractorid', 'userid')},
        ),
        migrations.AlterUniqueTogether(
            name='serviceapplications',
            unique_together={('serviceappid', 'serviceid')},
        ),
    ]
