from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('logout', views.logout, name='logout'),
    path('logout2', views.logoutProfile, name='logoutProfile'),
    path('deleteAccount', views.deleteAccount, name='deleteAccount'),
    path('services/', views.services_list, name='services_list'),
    path('booking/<str:pk>/', views.bookingStep1, name='booking1'),
    path('booking/<str:pk>/<str:description>/<str:date>/<str:time>/<str:address>/<str:aptnum>/<str:zipcode>/', views.bookingStep2, name='booking2'),
    path('becomeContractor/', views.becomeContractor, name='becomeContractor'),
    path('login/', views.login, name='login'),
    path('create_account/', views.createUserAccount, name="createUserAccount"),
    path('account/user_profile/', views.userProfile, name='userProfile'),
    path('account/user_profile/edit', views.userProfileEdit, name='userProfile_edit'),
    path('account/payment_methods/', views.userPayment, name='userPayment'),
    path('account/booking_history/', views.userBookingInfo, name='userBooking'),
    path('contractor/contractor_login/', views.contractorLogin, name='loginContractor'),
    path('contractor/contractor_profile/', views.contractorProfile, name='contractorProfile'),
    path('contractor/contractor_profile/edit', views.contractorProfileEdit, name='contractorProfile_edit'),
    path('contractor/service_record/', views.contractorServices, name='contractorServices'),
    path('contractor/service_record/apply', views.contractorServiceApp, name='contractorServiceApp'),
    path('contractor/rating_record/', views.contractorRatings, name='contractorRatings'),
    path('contractor/contract_history/', views.contractorContracts, name='contractorContracts'),
    path('contractor/schedule/', views.contractorSchedule, name='contractorSchedule'),
    path('administrator/admin_login/', views.adminLogin, name='loginAdministrator'),
    path('administrator/admin_profile/', views.adminProfile, name='administratorProfile'),
    path('administrator/users/', views.manageUsers, name='manageUsers'),
    path('administrator/contractors/', views.manageContractors, name='manageContractors'),
    path('administrator/contractor_applications/', views.manageContractorApp, name='manageApp1'),
    path('administrator/contractor_applications/approve/<str:id>', views.adminApproveApp, name='approveApp1'),
    path('administrator/contractor_applications/reject/<str:id>', views.adminRejectApp, name='rejectApp1'),
    path('administrator/service_applications/', views.manageServiceApp, name='manageApp2'),
    path('administrator/service_applications/approve/<str:id>', views.adminApproveApp2, name='approveApp2'),
    path('administrator/service_applications/reject/<str:id>', views.adminRejectApp2, name='rejectApp2'),
    path('administrator/<str:accountType>/<str:id>', views.adminDeleteAccount, name='adminDeleteAccount'),
    path('administrator/users/edit/<str:id>', views.adminEditUser, name='adminEditUser'),
]